version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: scrapy  
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scrapy
    ports:
      - "5432:5432"

  server:
    build: .
    command: /bin/sh -c /app/src/run.sh
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    ports:
      - "8080:8080"
